[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "teler"
version = "0.1.0"
description = "A helper library for FreJun Teler"
readme = "README.md"
license = { file = "LICENSE" }
authors = [{ name="FreJun", email="hello@frejun.com" }]
dependencies = ["websockets>=10.0"]
keywords = ["frejun", "teler", "sdk", "voip", "streaming"]

[project.urls]
Homepage = "https://github.com/frejun-tech/teler-py"